let songs = [
    {songName:"Fight Back",
    id :"1",
    tracklength:"3:30",
    filePath:"Audios/1.mp3",
    coverPath:"images/1.webp"},

    {songName:"Trapped",
    id :"2",
    tracklength:"4:30",
    filePath:"Audios/2.mp3",
    coverPath:"images/2.webp"},

    {songName:"No Sleep",
    id :"3",
    tracklength:"5:30",
    filePath:"Audios/3.mp3",
    coverPath:"images/3.webp"},
    
    {songName:"Light it Up",
    id :"4",
    tracklength:"3:30",
    filePath:"Audios/4.mp3",
    coverPath:"images/4.webp"},

    {songName:"Cold",
    id :"5",
    tracklength:"4:30",
    filePath:"Audios/5.mp3",
    coverPath:"images/5.webp"},

    {songName:"Failure",
    id :"6",
    tracklength:"5:30",
    filePath:"Audios/6.mp3",
    coverPath:"images/6.webp"},

    {songName:"Brave",
    id :"7",
    tracklength:"3:30",
    filePath:"Audios/7.mp3",
    coverPath:"images/7.webp"},

    {songName:"As You Fade",
    id :"8",
    tracklength:"4:30",
    filePath:"Audios/8.mp3",
    coverPath:"images/8.webp"},

    {songName:"Grateful",
    id :"9",
    tracklength:"5:30",
    filePath:"Audios/9.mp3",
    coverPath:"images/9.webp"},
];